# This workflow will build a .NET project

name: .NET

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    - uses: robinraju/release-downloader@v1.7
      with:
        tag: "v1.0.5"
        fileName: "Av1ador.zip"
    - name: Extract Release
      run: 7z e Av1ador.zip -oD:bin\Release\ Av1ador\*
    - name: Build DotNET35
      run: |
        cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
        .\MSBuild.exe $Env:GITHUB_WORKSPACE\Av1ador.sln /p:Configuration=Release
    - name: Archive Release
      run: 7z a -tzip Av1ador-nightly.zip .\bin\Release\*.exe .\bin\Release\*.dll .\bin\Release\*.bin .\bin\Release\*.sofa
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "Av1ador-nightly.zip"
        artifactContentType: application/zip
        prerelease: false
        allowUpdates: true
        removeArtifacts: true
        replacesArtifacts: true
        tag: Nightly
        name: Nightly
        makeLatest: true
